#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

date_default_timezone_set(getenv('TIMEZONE'));

$application = new \Symfony\Component\Console\Application();
$application->add(new \Maschinenraum\FbApi\Command\ListCallsCommand());
$application->run();
